#!/usr/bin/env python3
"""
Generate comprehensive English-Vietnamese medical terminology translations.
All translations follow Vietnamese medical standards and terminology conventions.
"""

translations = {
    "Paracetamol poisoning": "Ngộ độc Paracetamol",
    "Acromegaly": "To đầu chi",
    "Actinic keratosis": "Dày sừng quang hóa",
    "Congenital adrenal hyperplasia": "Tăng sản thượng thận bẩm sinh",
    "Adrenocortical carcinoma": "Ung thư vỏ thượng thận",
    "Alcohol withdrawal syndrome": "Hội chứng cai rượu",
    "Alopecia areata": "Rụng tóc từng mảng",
    "Altitude sickness": "Say độ cao",
    "Amblyopia": "Nhược thị",
    "Amoebiasis": "Bệnh amip",
    "Anaplasmosis": "Bệnh Anaplasma",
    "Anaplastic astrocytoma": "U sao bào thoái sản",
    "Anorexia nervosa": "Chán ăn tâm thần",
    "Anthrax": "Bệnh than",
    "Anticholinergic": "Kháng cholinergic",
    "Antisialagogue": "Thuốc giảm tiết nước bọt",
    "Aphthous stomatitis": "Viêm miệng áp-tơ",
    "APL": "Bạch cầu cấp dòng tiền tủy bào",
    "Apnea of prematurity": "Ngưng thở ở trẻ sinh non",
    "Arsenic poisoning": "Ngộ độc asen",
    "Ascariasis": "Bệnh giun đũa",
    "Assisted reproductive technology": "Hỗ trợ sinh sản",
    "Autism spectrum": "Rối loạn phổ tự kỷ",
    "Babesiosis": "Bệnh Babesia",
    "Induced coma": "Hôn mê nhân tạo",
    "Barretts esophagus": "Thực quản Barrett",
    "Emotional and behavioral disorders": "Rối loạn cảm xúc và hành vi",
    "Benign prostatic hyperplasia": "Tăng sản lành tính tuyến tiền liệt",
    "Benzodiazepine overdose": "Quá liều Benzodiazepine",
    "Thiamine deficiency": "Thiếu Thiamine (vitamin B1)",
    "Beta blocker": "Thuốc chẹn beta",
    "Biliary atresia": "Teo đường mật bẩm sinh",
    "Binge eating disorder": "Rối loạn ăn vô độ",
    "Blastic plasmacytoid dendritic cell neoplasm": "Tân sinh tế bào tua plasmacytoid dạng blast",
    "Osteomyelitis": "Viêm tủy xương",
    "Botulism": "Ngộ độc botulinum",
    "Colonoscopy": "Nội soi đại tràng",
    "Bronchopulmonary dysplasia": "Loạn sản phế quản phổi",
    "Brucellosis": "Bệnh Brucella",
    "Burning mouth syndrome": "Hội chứng miệng bỏng rát",
    "Bursitis": "Viêm bao hoạt dịch",
    "Clostridioides difficile infection": "Nhiễm Clostridioides difficile",
    "Cachexia": "Suy kiệt",
    "Calcium channel blocker toxicity": "Ngộ độc thuốc chẹn kênh canxi",
    "Campylobacteriosis": "Nhiễm Campylobacter",
    "Fungemia": "Nhiễm nấm máu",
    "Capillariasis": "Bệnh giun Capillaria",
    "Cardiac stress test": "Nghiệm pháp gắng sức tim",
    "Systemic primary carnitine deficiency": "Thiếu carnitine nguyên phát toàn thân",
    "Precocious puberty": "Dậy thì sớm",
    "Cervical effacement": "Xóa cổ tử cung",
    "Cervicitis": "Viêm cổ tử cung",
    "Chancroid": "Hạ cam mềm",
    "Cholangiocarcinoma": "Ung thư đường mật",
    "Cholera": "Bệnh tả",
    "Invasive hydatidiform mole": "Chửa trứng xâm lấn",
    "Choriocarcinoma": "Ung thư nguyên bào nuôi",
    "Claudication": "Đau cách hồi",
    "Colic": "Cơn đau quặn",
    "Common cold": "Cảm lạnh thông thường",
    "Genital wart": "Mụn cóc sinh dục",
    "Convex": "Lồi",
    "Croup": "Viêm thanh khí phế quản",
    "Cryopyrin-associated periodic syndrome": "Hội chứng chu kỳ liên quan Cryopyrin",
    "Cushings syndrome": "Hội chứng Cushing",
    "Cyanide poisoning": "Ngộ độc Cyanide",
    "Cycloplegia": "Liệt thể mi",
    "Cystic fibrosis": "Xơ nang",
    "Cysticercosis": "Bệnh ấu trùng sán dải heo",
    "Cystinosis": "Bệnh Cystin niệu",
    "Cystinuria": "Cystin niệu",
    "Isosporiasis": "Bệnh Isospora",
    "Gastroparesis": "Liệt dạ dày",
    "Delayed puberty": "Dậy thì muộn",
    "Dermatitis herpetiformis": "Viêm da dạng herpes",
    "Dermatofibrosarcoma protuberans": "Sarcom xơ bì lồi",
    "Skin condition": "Bệnh da liễu",
    "Dexamethasone suppression test": "Nghiệm pháp ức chế Dexamethasone",
    "Type 1 diabetes": "Đái tháo đường type 1",
    "Type 2 diabetes": "Đái tháo đường type 2",
    "Irritant diaper dermatitis": "Viêm da tã lót do kích ứng",
    "Digoxin toxicity": "Ngộ độc Digoxin",
    "Discoid lupus erythematosus": "Lupus ban đỏ dạng đĩa",
    "Dry eye syndrome": "Hội chứng khô mắt",
    "Duchenne muscular dystrophy": "Loạn dưỡng cơ Duchenne",
    "Dupuytrens contracture": "Co rút Dupuytren",
    "Eating disorder": "Rối loạn ăn uống",
    "Ectasia": "Giãn",
    "Ehrlichiosis": "Bệnh Ehrlichia",
    "Endometriosis": "Lạc nội mạc tử cung",
    "Endometritis": "Viêm nội mạc tử cung",
    "Endophthalmitis": "Viêm nội nhãn",
    "Tracheal intubation": "Đặt nội khí quản",
    "Epididymitis": "Viêm mào tinh hoàn",
    "Esophagitis": "Viêm thực quản",
    "Erysipelas": "Viêm quầng",
    "Erysipeloid": "Bệnh giả đơn độc",
    "Esotropia": "Lé trong",
    "Ethylene glycol poisoning": "Ngộ độc ethylene glycol",
    "Ewing sarcoma": "Sarcom Ewing",
    "Exocrine pancreatic insufficiency": "Suy tụy ngoại tiết",
    "Exposure keratopathy": "Bệnh giác mạc do phơi nhiễm",
    "Failure to thrive": "Chậm phát triển thể chất",
    "Familial Mediterranean fever": "Sốt Địa Trung Hải gia đình",
    "Fasciolosis": "Bệnh sán lá gan lớn",
    "Food allergy": "Dị ứng thực phẩm",
    "Endoscopic foreign body retrieval": "Lấy dị vật qua nội soi",
    "Labial fusion": "Dính môi âm hộ",
    "Gastric erosion": "Trợt dạ dày",
    "Gestational trophoblastic disease": "Bệnh nguyên bào nuôi thai kỳ",
    "Giardiasis": "Bệnh Giardia",
    "Gingivitis": "Viêm nướu",
    "Glioblastoma": "U nguyên bào thần kinh đệm",
    "Gold": "Vàng (kim loại)",
    "Granuloma annulare": "U hạt dạng vòng",
    "Helicobacter pylori": "Vi khuẩn Helicobacter pylori",
    "Hemorrhoid": "Trĩ",
    "Heparin-induced thrombocytopenia": "Giảm tiểu cầu do Heparin",
    "Hepatic porphyria": "Bệnh porphyria gan",
    "Hereditary hemorrhagic telangiectasia": "Giãn mao mạch xuất huyết di truyền",
    "Orotic aciduria": "Axit orotic niệu",
    "Herpes labialis": "Herpes môi",
    "Heterotopic ossification": "Cốt hóa lạc chỗ",
    "Hirsutism": "Rậm lông",
    "Hookworm infection": "Nhiễm giun móc",
    "Molar pregnancy": "Chửa trứng",
    "Hyperaldosteronism": "Cường aldosteron",
    "Hyperkeratosis": "Tăng sừng hóa",
    "Hypoestrogenism": "Giảm estrogen",
    "Hypophosphatasia": "Hạ phosphatase",
    "Hypoprothrombinemia": "Giảm prothrombin máu",
    "Hair loss": "Rụng tóc",
    "Ichthyosis vulgaris": "Bệnh vảy cá thông thường",
    "Immune thrombocytopenic purpura": "Xuất huyết giảm tiểu cầu miễn dịch",
    "Impetigo": "Chốc lở",
    "Infantile hemangioma": "U máu ở trẻ em",
    "Infection prevention and control": "Phòng ngừa và kiểm soát nhiễm khuẩn",
    "Intermittent claudication": "Đau cách hồi",
    "Intermittent explosive disorder": "Rối loạn bùng nổ từng cơn",
    "Interstitial cystitis": "Viêm bàng quang kẽ",
    "Iron poisoning": "Ngộ độc sắt",
    "Iron supplement": "Bổ sung sắt",
    "Juvenile myoclonic epilepsy": "Động kinh giật cơ vị thành niên",
    "Kaposis sarcoma": "Sarcom Kaposi",
    "Keloid": "Sẹo lồi",
    "Keratoconus": "Giác mạc hình nón",
    "Keratosis follicularis": "Dày sừng nang lông",
    "Labor induction": "Khởi phát chuyển dạ",
    "Childbirth": "Sinh đẻ",
    "Lambert–Eaton myasthenic syndrome": "Hội chứng nhược cơ Lambert-Eaton",
    "Larva migrans": "Ấu trùng di chuyển",
    "Lead poisoning": "Ngộ độc chì",
    "Leishmaniasis": "Bệnh Leishmania",
    "Lentigo": "Đồi mồi",
    "Leprosy": "Bệnh phong",
    "Liver abscess": "Áp xe gan",
    "Liver fluke": "Sán lá gan",
    "Lymphogranuloma venereum": "U hạt bạch huyết hoa liễu",
    "Lysosomal acid lipase deficiency": "Thiếu lipase acid lysosome",
    "Maceration": "Ngâm mủn",
    "Malaria": "Sốt rét",
    "Malaria prophylaxis": "Dự phòng sốt rét",
    "Pattern hair loss": "Rụng tóc kiểu mẫu",
    "Malignant hyperthermia": "Tăng thân nhiệt ác tính",
    "Breast pain": "Đau vú",
    "Megaloblastic anemia": "Thiếu máu nguyên hồng cầu khổng lồ",
    "Mercury poisoning": "Ngộ độc thủy ngân",
    "Mesothelioma": "U trung biểu mô",
    "Methanol toxicity": "Ngộ độc methanol",
    "Mevalonate kinase deficiency": "Thiếu mevalonate kinase",
    "Microscopic polyangiitis": "Viêm đa vi mạch",
    "Microsporidiosis": "Bệnh Microsporidia",
    "Miscarriage": "Sẩy thai",
    "Hurler syndrome": "Hội chứng Hurler",
    "Hunter syndrome": "Hội chứng Hunter",
    "Maroteaux–Lamy syndrome": "Hội chứng Maroteaux-Lamy",
    "Sly syndrome": "Hội chứng Sly",
    "Mucormycosis": "Bệnh nấm Mucor",
    "Multifocal motor neuropathy": "Bệnh thần kinh vận động đa ổ",
    "Necrobiosis lipoidica": "Hoại tử mỡ",
    "Neonatal withdrawal": "Hội chứng cai ở trẻ sơ sinh",
    "Neurocysticercosis": "Ấu trùng sán lợn não",
    "Neurogenic bladder dysfunction": "Rối loạn bàng quang thần kinh",
    "Neurosyphilis": "Giang mai thần kinh",
    "Neurotrophic keratitis": "Viêm giác mạc dinh dưỡng thần kinh",
    "Nightmare": "Ác mộng",
    "Nocturnal enuresis": "Đái dầm ban đêm",
    "Onchocerciasis": "Bệnh giun chỉ Onchocerca",
    "Onychomycosis": "Nấm móng",
    "Neonatal conjunctivitis": "Viêm kết mạc sơ sinh",
    "Osteogenesis imperfecta": "Tạo xương bất toàn",
    "Osteopetrosis": "Xương hóa đá",
    "Otitis externa": "Viêm tai ngoài",
    "Ovarian hyperstimulation syndrome": "Hội chứng quá kích buồng trứng",
    "Overactive bladder": "Bàng quang tăng hoạt",
    "Ovulation induction": "Kích thích phóng noãn",
    "Paracentesis": "Chọc dịch",
    "Paroxysmal nocturnal hemoglobinuria": "Đái huyết sắc tố kịch phát ban đêm",
    "Patent ductus arteriosus": "Còn ống động mạch",
    "Head lice infestation": "Nhiễm chấy đầu",
    "Pediculosis corporis": "Nhiễm rận thân",
    "Pediculosis pubis": "Nhiễm rận mu",
    "Pellagra": "Bệnh Pellagra",
    "Pemphigus vulgaris": "Pemphigus thông thường",
    "Periodic paralysis": "Liệt chu kỳ",
    "Periodontal disease": "Bệnh nha chu",
    "Pernicious anemia": "Thiếu máu ác tính",
    "Peroxisomal disorder": "Rối loạn peroxisome",
    "PID": "Viêm vùng chậu",
    "Pinworm infection": "Nhiễm giun kim",
    "Pleurodesis": "Dính màng phổi",
    "Polycystic ovary syndrome": "Hội chứng buồng trứng đa nang",
    "Porphyria": "Bệnh Porphyria",
    "Postherpetic neuralgia": "Đau thần kinh sau Herpes",
    "Post-traumatic stress disorder": "Rối loạn stress sau sang chấn",
    "Abortion": "Phá thai",
    "Premenstrual dysphoric disorder": "Rối loạn khí sắc tiền kinh nguyệt",
    "Premenstrual syndrome": "Hội chứng tiền kinh nguyệt",
    "Primary biliary cholangitis": "Viêm đường mật mật nguyên phát",
    "CD30+ cutaneous T-cell lymphoma": "Lymphoma tế bào T da CD30+",
    "Proctitis": "Viêm trực tràng",
    "Prostatitis": "Viêm tuyến tiền liệt",
    "Pruritus ani": "Ngứa hậu môn",
    "Pseudobulbar affect": "Rối loạn cảm xúc giả hành",
    "Pud": "Loét dạ dày tá tràng",
    "Pulmonary hypertension": "Tăng áp phổi",
    "Ventricular tachycardia": "Nhịp nhanh thất",
    "Pyogenic granuloma": "U hạt mủ",
    "Vitamin B6": "Vitamin B6",
    "Rapid eye movement sleep behavior disorder": "Rối loạn hành vi giấc ngủ REM",
    "Rapid sequence induction": "Khởi mê nhanh",
    "Rat-bite fever": "Sốt do chuột cắn",
    "Raynaud syndrome": "Hội chứng Raynaud",
    "Refractive surgery": "Phẫu thuật khúc xạ",
    "Renal colic": "Cơn đau quặn thận",
    "Rhabdomyosarcoma": "Sarcom cơ vân",
    "Rheumatic fever": "Sốt thấp khớp",
    "Riboflavin": "Riboflavin (Vitamin B2)",
    "Rickets": "Còi xương",
    "Rocky Mountain spotted fever": "Sốt phát ban Rocky Mountain",
    "Rosacea": "Trứng cá đỏ",
    "Roughness": "Thô ráp",
    "Nematode infection": "Nhiễm giun tròn",
    "Salmonellosis": "Nhiễm Salmonella",
    "Scabies": "Ghẻ",
    "Schilling test": "Nghiệm pháp Schilling",
    "Schistosomiasis": "Bệnh sán máng",
    "Scorpion sting": "Bọ cạp đốt",
    "Scurvy": "Bệnh scorbut",
    "Seasonal affective disorder": "Rối loạn cảm xúc theo mùa",
    "Seborrhoeic dermatitis": "Viêm da tiết bã",
    "Seborrheic keratosis": "Dày sừng tiết bã",
    "Sézary disease": "Bệnh Sézary",
    "Shigellosis": "Bệnh Shigella (lỵ trực khuẩn)",
    "Short bowel syndrome": "Hội chứng ruột ngắn",
    "Hypersalivation": "Tăng tiết nước bọt",
    "Night terror": "Hoảng sợ ban đêm",
    "Smallpox": "Bệnh đậu mùa",
    "Snakebite": "Rắn cắn",
    "Spasmodic dysphonia": "Loạn phát âm co thắt",
    "Spider bite": "Nhện cắn",
    "Spontaneous bacterial peritonitis": "Viêm phúc mạc nhiễm khuẩn tự phát",
    "Sporotrichosis": "Bệnh nấm Sporothrix",
    "Strabismus": "Lác mắt",
    "Strongyloidiasis": "Bệnh giun lươn",
    "Sympathetic ophthalmia": "Viêm mắt giao cảm",
    "Eucestoda": "Sán dây",
    "Tendinopathy": "Bệnh lý gân",
    "Tenosynovial giant cell tumor": "U tế bào khổng lồ bao gân",
    "Tetanus": "Uốn ván",
    "Thrombocythemia": "Tăng tiểu cầu",
    "Tinea barbae": "Nấm vùng râu",
    "Tinea capitis": "Nấm da đầu",
    "Tinea corporis": "Nấm thân",
    "Tinea cruris": "Nấm bẹn",
    "Tinea nigra": "Nấm da đen",
    "Athletes foot": "Nấm bàn chân",
    "Tinea versicolor": "Lang ben",
    "Tocolytic": "Thuốc giảm co tử cung",
    "Tourette syndrome": "Hội chứng Tourette",
    "Toxoplasmosis": "Bệnh Toxoplasma",
    "Trachoma": "Bệnh mắt hột",
    "Travelers diarrhea": "Tiêu chảy du lịch",
    "Trichinosis": "Bệnh giun xoắn",
    "Trichomoniasis": "Bệnh Trichomonas",
    "Tricyclic antidepressant overdose": "Quá liều thuốc chống trầm cảm ba vòng",
    "Trigeminal neuralgia": "Đau dây thần kinh sinh ba",
    "Tropical sprue": "Sprue nhiệt đới",
    "Tuberculosis management": "Điều trị lao",
    "Typhoid fever": "Sốt thương hàn",
    "Weight loss": "Giảm cân",
    "Urethritis": "Viêm niệu đạo",
    "Sodium bicarbonate": "Natri bicarbonat",
    "Bacterial vaginosis": "Viêm âm đạo do vi khuẩn",
    "Nonallergic rhinitis": "Viêm mũi không dị ứng",
    "Ventriculitis": "Viêm não thất",
    "Vitamin D deficiency": "Thiếu vitamin D",
    "Vitamin E deficiency": "Thiếu vitamin E",
    "Waldenström macroglobulinemia": "Bệnh Waldenström",
    "Wart": "Mụn cóc",
    "Wernicke encephalopathy": "Bệnh não Wernicke",
    "Wilms tumor": "U Wilms",
    "Wrinkle": "Nếp nhăn",
    "X-linked hypophosphatemia": "Hạ phospho máu liên kết X",
    "Xerophthalmia": "Khô mắt",
    "Xerostomia": "Khô miệng",
    "Yersiniosis": "Nhiễm Yersinia",
    "Zinc deficiency": "Thiếu kẽm",
    "Zollinger–Ellison syndrome": "Hội chứng Zollinger-Ellison",
    "Skeletal fluorosis": "Nhiễm fluor xương",
    "Amylase": "Amylase",
    "Ectopic calcification": "Vôi hóa lạc chỗ",
    "Bullous keratopathy": "Bệnh giác mạc bọng",
    "Hostility": "Thù địch",
    "Cold sensitivity": "Nhạy cảm với lạnh",
    "Spontaneous coronary artery dissection": "Bóc tách động mạch vành tự phát",
    "Bleeding diathesis": "Cơ địa chảy máu",
    "Breast development": "Phát triển vú",
    "Asterixis": "Run vẫy (Asterixis)",
    "Tetraplegia": "Liệt tứ chi",
    "Menstrual disorder": "Rối loạn kinh nguyệt",
    "Hyperkinesia": "Tăng vận động",
    "Vertebral compression fracture": "Gãy xẹp đốt sống",
    "Lung abscess": "Áp xe phổi",
    "Irritation": "Kích ứng",
    "Voice change": "Thay đổi giọng nói",
    "Abdominal pain": "Đau bụng",
    "Ischemia": "Thiếu máu cục bộ",
    "Taste": "Vị giác",
    "Polyarteritis nodosa": "Viêm đa động mạch nút",
    "Aplastic anemia": "Thiếu máu bất sản",
    "Hepatocellular carcinoma": "Ung thư biểu mô tế bào gan",
    "Chorioamnionitis": "Viêm màng ối",
    "Gray baby syndrome": "Hội chứng em bé xám",
    "Spasticity": "Co cứng",
    "Standing": "Đứng",
    "Pituitary apoplexy": "Đột quỵ tuyến yên",
    "Cholestasis": "Ứ mật",
    "Cerebral infarction": "Nhồi máu não",
    "Neutropenic enterocolitis": "Viêm ruột do giảm bạch cầu trung tính",
    "Hemorrhagic gastroenteritis": "Viêm dạ dày ruột xuất huyết",
    "Wheal": "Sẩn phù",
    "Fasciculation": "Rung giật cơ",
    "Colorectal polyp": "Polyp đại trực tràng",
    "Mammary tumor": "U vú",
    "Lymphedema": "Phù bạch huyết",
    "Gastroesophageal reflux disease": "Bệnh trào ngược dạ dày thực quản",
    "Neoplasm": "Tân sinh (khối u)",
    "Autosensitization dermatitis": "Viêm da tự mẫn cảm",
    "Human skin": "Da người",
    "Salicylate poisoning": "Ngộ độc salicylat",
    "Anorexia (symptom)": "Chán ăn (triệu chứng)",
    "Crystalluria": "Tinh thể niệu",
    "Adhesion (medicine)": "Dính (y khoa)",
    "Renal osteodystrophy": "Loạn dưỡng xương do thận",
    "Bowel infarction": "Nhồi máu ruột",
    "Adrenal insufficiency": "Suy thượng thận",
    "Hypertrophic cardiomyopathy": "Bệnh cơ tim phì đại",
    "Linear IgA bullous dermatosis": "Bệnh da bọng IgA tuyến tính",
    "Burping": "Ợ hơi",
    "Cardiac fibrosis": "Xơ hóa tim",
    "Goodpasture syndrome": "Hội chứng Goodpasture",
    "Water intoxication": "Ngộ độc nước",
    "Confusion": "Lú lẫn",
    "Pulmonary fibrosis": "Xơ phổi",
    "Peripheral neuropathy": "Bệnh thần kinh ngoại biên",
    "Calciphylaxis": "Vôi hóa mạch máu",
    "Hair bleaching": "Tẩy trắng tóc",
    "Malabsorption": "Kém hấp thu",
    "Urinary cast": "Trụ niệu",
    "Stupor": "Sững sờ (stupor)",
    "Catatonia": "Căng trương lực",
    "Ischemic colitis": "Viêm đại tràng thiếu máu",
    "Leukocytosis": "Tăng bạch cầu",
    "Rhinitis medicamentosa": "Viêm mũi do thuốc",
    "Primary sclerosing cholangitis": "Viêm đường mật xơ hóa nguyên phát",
    "Lipoma": "U mỡ",
    "Cholinergic crisis": "Cơn cholinergic",
    "Renal tubular acidosis": "Toan hóa ống thận",
    "Biliary colic": "Cơn đau quặn mật",
    "Splenic infarction": "Nhồi máu lách",
    "Abdominal compartment syndrome": "Hội chứng chèn ép khoang bụng",
    "Hemolytic–uremic syndrome": "Hội chứng tán huyết ure máu cao",
    "Atelectasis": "Xẹp phổi",
    "Parosmia": "Rối loạn khứu giác",
    "Hematospermia": "Xuất tinh máu",
    "Preterm birth": "Sinh non",
    "Takotsubo cardiomyopathy": "Bệnh cơ tim Takotsubo",
    "Trismus": "Cứng hàm",
    "Acute intermittent porphyria": "Porphyria cấp từng cơn",
    "Melanosis coli": "Tăng sắc tố đại tràng",
    "Dissociation": "Phân ly",
    "Heart murmur": "Tiếng thổi tim",
    "Amyloid-related imaging abnormalities": "Bất thường hình ảnh liên quan amyloid",
    "Parotitis": "Viêm tuyến mang tai",
    "Bladder sphincter dyssynergia": "Loạn đồng vận cơ vòng bàng quang",
    "Emergence delirium": "Sảng sau gây mê",
    "Cauda equina syndrome": "Hội chứng đuôi ngựa",
    "Emotional disturbance": "Rối loạn cảm xúc",
    "Freckle": "Tàn nhang",
    "Facial nerve paralysis": "Liệt dây thần kinh mặt",
    "Seminoma": "U tinh bào",
    "Acute hemorrhagic edema of infancy": "Phù xuất huyết cấp ở trẻ nhỏ",
    "Livedo reticularis": "Lưới tím da",
    "Cardiac arrest": "Ngừng tim",
    "Bone marrow failure": "Suy tủy xương",
    "Mental disorder": "Rối loạn tâm thần",
    "Blackwater fever": "Sốt nước tiểu đen",
    "Cannabinoid hyperemesis syndrome": "Hội chứng nôn do cần sa",
    "Fecal incontinence": "Tiểu không tự chủ phân",
    "Ichthyosis": "Bệnh vảy cá",
    "Lichen planus": "Lichen phẳng",
    "Erythema multiforme major": "Hồng ban đa dạng thể nặng",
    "Prelabor rupture of membranes": "Vỡ ối sớm",
    "Pleocytosis": "Tăng tế bào dịch não tủy",
    "Precordium": "Vùng trước tim",
    "Milk-alkali syndrome": "Hội chứng sữa-kiềm",
    "Aseptic meningitis": "Viêm màng não vô khuẩn",
    "Irregular menstruation": "Kinh nguyệt không đều",
    "Hemarthrosis": "Tràn máu khớp",
    "Fatty liver disease": "Bệnh gan nhiễm mỡ",
    "Stomach rumble": "Sôi bụng",
    "Microhematuria": "Tiểu máu vi thể",
    "Necrolytic migratory erythema": "Hồng ban hoại tử di chuyển",
    "Hemoglobinuria": "Huyết sắc tố niệu",
    "Uterine rupture": "Vỡ tử cung",
    "Pneumatosis intestinalis": "Tràn khí thành ruột",
    "Multiple organ dysfunction syndrome": "Hội chứng rối loạn đa cơ quan",
    "Dream": "Giấc mơ",
    "Pleurisy": "Viêm màng phổi",
    "Osteosarcoma": "Sarcom xương",
    "List of causes of genital pain": "Danh sách nguyên nhân đau sinh dục",
    "Tachycardia": "Nhịp tim nhanh",
    "Respiratory alkalosis": "Kiềm hô hấp",
    "Fundic gland polyp": "Polyp tuyến đáy vị",
    "Testicular atrophy": "Teo tinh hoàn",
    "Hemiparesis": "Liệt nửa người nhẹ",
    "Radiculopathy": "Bệnh rễ thần kinh",
    "Hypoproteinemia": "Giảm protein máu",
    "Vertigo": "Chóng mặt",
    "Hypokinesia": "Giảm vận động",
    "Tracheobronchial injury": "Chấn thương khí phế quản",
    "Phimosis": "Hẹp bao quy đầu",
    "Ingrown nail": "Móng chọc thịt",
    "Opisthotonus": "Ưỡn cong người",
    "Intussusception": "Lồng ruột",
    "Biliary sludge": "Bùn mật",
    "Hyperpigmentation": "Tăng sắc tố da",
    "Fournier gangrene": "Hoại thư Fournier",
    "Cerebral vasculitis": "Viêm mạch não",
    "Human skin color": "Màu da người",
    "Flushing (physiology)": "Đỏ bừng (sinh lý)",
    "Diabetic neuropathy": "Bệnh thần kinh đái tháo đường",
    "Necrotizing enterocolitis": "Viêm ruột hoại tử",
    "Strain (injury)": "Căng cơ",
    "Hunger": "Đói",
    "Acute-phase protein": "Protein giai đoạn cấp",
    "Nitrovasodilator": "Thuốc giãn mạch nitro",
    "Muscle atrophy": "Teo cơ",
    "Myoclonus": "Giật cơ",
    "Warfarin resistance": "Kháng Warfarin",
    "Pulmonary edema": "Phù phổi",
    "Fecal impaction": "Phân bite tắc",
    "Sterility": "Vô sinh",
    "Porphyria cutanea tarda": "Porphyria da muộn",
    "Pyoderma": "Viêm da mủ",
    "Dopamine dysregulation syndrome": "Hội chứng rối loạn dopamine",
    "Cognitive deficit": "Suy giảm nhận thức",
    "Blood type": "Nhóm máu",
    "Vaginal lubrication": "Dịch nhờn âm đạo",
    "Amnesia": "Mất trí nhớ",
    "Ovarian torsion": "Xoắn buồng trứng",
    "Hyperchloremia": "Tăng clo máu",
    "Isotonic hyponatremia": "Hạ natri máu đẳng trương",
    "Hypoventilation": "Giảm thông khí",
    "Henoch–Schönlein purpura": "Ban xuất huyết Henoch-Schönlein",
    "Erythema": "Hồng ban",
    "Thyroid adenoma": "U tuyến giáp lành tính",
    "Lymphadenopathy": "Hạch to",
    "Pseudohyperaldosteronism": "Giả cường aldosteron",
    "Vaginal bleeding": "Chảy máu âm đạo",
    "Periostitis": "Viêm màng xương",
    "Aphonia": "Mất tiếng",
    "Bronchiolitis obliterans": "Viêm tiểu phế quản tắc nghẽn",
    "Hypohidrosis": "Giảm tiết mồ hôi",
    "Miliaria": "Rôm sảy",
    "Acute liver failure": "Suy gan cấp",
    "Perioral dermatitis": "Viêm da quanh miệng",
    "Hemolytic anemia": "Thiếu máu tán huyết",
    "Retroperitoneal fibrosis": "Xơ hóa sau phúc mạc",
    "Rhabdomyolysis": "Tiêu cơ vân",
    "Photodermatitis": "Viêm da do ánh sáng",
    "Multiple birth": "Đa thai",
    "Hypervitaminosis": "Thừa vitamin",
    "Hemangioma": "U máu",
    "Aortic aneurysm": "Phình động mạch chủ",
    "Reticulocytosis": "Tăng hồng cầu lưới",
    "Lipomatosis": "Đa u mỡ",
    "Genital ulcer": "Loét sinh dục",
    "Macrocytosis": "Hồng cầu to",
    "Propofol infusion syndrome": "Hội chứng truyền Propofol",
    "Brachial plexus injury": "Tổn thương đám rối cánh tay",
    "Hepatic artery thrombosis": "Huyết khối động mạch gan",
    "Gynecologic hemorrhage": "Xuất huyết phụ khoa",
    "Eosinophilia": "Tăng bạch cầu ái toan",
    "Amniotic fluid embolism": "Thuyên tắc ối",
    "Bells palsy": "Liệt Bell",
    "Toxic leukoencephalopathy": "Bệnh chất trắng não do độc chất",
    "Colitis": "Viêm đại tràng",
    "Ascending cholangitis": "Viêm đường mật ngược dòng",
    "Cutaneous small-vessel vasculitis": "Viêm mạch nhỏ da",
    "Fissure": "Nứt kẽ",
    "Refeeding syndrome": "Hội chứng nuôi ăn lại",
    "Paraplegia": "Liệt hai chi dưới",
    "Congenital afibrinogenemia": "Vô fibrinogen máu bẩm sinh",
    "Breast cyst": "Nang vú",
    "Uterine contraction": "Co tử cung",
    "Uterine perforation": "Thủng tử cung",
    "Pediculosis": "Nhiễm rận",
    "Laxative": "Thuốc nhuận tràng",
    "Hemorrhagic cystitis": "Viêm bàng quang xuất huyết",
    "Placental abruption": "Bong nhau non",
    "Uterus": "Tử cung",
    "Stenosis": "Hẹp",
    "Opioid use disorder": "Rối loạn sử dụng opioid",
    "Testicular pain": "Đau tinh hoàn",
    "Telangiectasia": "Giãn mao mạch",
    "Ophthalmoparesis": "Liệt cơ vận nhãn",
    "Body odor": "Mùi cơ thể",
    "Hepatitis": "Viêm gan",
    "Hypoesthesia": "Giảm cảm giác",
    "Disinhibition": "Mất ức chế",
    "Substance dependence": "Phụ thuộc chất",
    "Cranial nerve disease": "Bệnh dây thần kinh sọ",
    "Arachnoiditis": "Viêm màng nhện",
    "Hyperosmolar hyperglycemic state": "Tình trạng tăng áp lực thẩm thấu tăng đường huyết",
    "Clitoromegaly": "Phì đại âm vật",
    "Anasarca": "Phù toàn thân",
    "Stomach": "Dạ dày",
    "Intellectual disability": "Khuyết tật trí tuệ",
    "Anabolic steroid": "Steroid đồng hóa",
    "Depersonalization": "Giải thể nhân cách",
    "Appendicitis": "Viêm ruột thừa",
    "Uterine sarcoma": "Sarcom tử cung",
    "Cockayne syndrome": "Hội chứng Cockayne",
    "Craniosynostosis": "Dính khớp sọ sớm",
    "Arthropathy": "Bệnh khớp",
    "Abscess": "Áp xe",
    "Black eye": "Bầm mắt",
    "Hypoactive sexual desire disorder": "Rối loạn giảm ham muốn tình dục",
    "Ileitis": "Viêm hồi tràng",
    "Shake": "Rung lắc",
    "Postpartum bleeding": "Chảy máu sau sinh",
    "Autonomic dysreflexia": "Loạn phản xạ tự chủ",
    "Coronary vasospasm": "Co thắt mạch vành",
    "Encephalomyelitis": "Viêm não tủy",
    "Pemphigus foliaceus": "Pemphigus lá",
    "Eosinophilic pneumonia": "Viêm phổi tăng bạch cầu ái toan",
    "Glycosuria": "Đường niệu",
    "Hyperventilation": "Tăng thông khí",
    "Ataxia": "Thất điều",
    "Paleness": "Nhợt nhạt",
    "Rectal tenesmus": "Mót rặn trực tràng",
    "Acute pancreatitis": "Viêm tụy cấp",
    "Lactation suppression": "Ức chế tiết sữa",
    "Epithelial dysplasia": "Loạn sản biểu mô",
    "Purple glove syndrome": "Hội chứng găng tay tím",
    "Preadolescence": "Tiền dậy thì",
    "Dilated cardiomyopathy": "Bệnh cơ tim giãn",
    "Hypertonia": "Tăng trương lực cơ",
    "Blister": "Bọng nước",
    "Livedoid dermatitis": "Viêm da dạng lưới tím",
    "Empyema": "Tràn mủ",
    "Gait abnormality": "Bất thường dáng đi",
    "Eczema herpeticum": "Eczema herpes",
    "Pulmonary embolism": "Thuyên tắc phổi",
    "Metabolic alkalosis": "Kiềm chuyển hóa",
    "Hyperproteinemia": "Tăng protein máu",
    "Alcohol intolerance": "Không dung nạp rượu",
    "Hypotonic-hyporesponsive episode": "Cơn giảm trương lực - giảm đáp ứng",
    "Esophageal rupture": "Vỡ thực quản",
    "Leukorrhea": "Khí hư",
    "Crackles": "Ran nổ",
    "Intermenstrual bleeding": "Chảy máu giữa kỳ kinh",
    "Sciatica": "Đau thần kinh tọa",
    "Casting defect": "Khuyết tật khuôn đúc",
    "Libido": "Ham muốn tình dục",
    "Embolic and thrombotic events after COVID-19 vaccination": "Biến cố thuyên tắc và huyết khối sau tiêm vắc-xin COVID-19",
    "Vasospasm": "Co thắt mạch",
    "Hydronephrosis": "Thận ứ nước",
    "Penile pain": "Đau dương vật",
    "Tracheoesophageal fistula": "Rò khí quản-thực quản",
    "Hemoperitoneum": "Tràn máu phúc mạc",
    "Orthostatic hypotension": "Hạ huyết áp tư thế",
    "Hyposmia": "Giảm khứu giác",
    "Birth defect": "Dị tật bẩm sinh",
    "Pyoderma gangrenosum": "Viêm da hoại thư mủ",
    "Lactic acidosis": "Toan lactic",
    "Pulmonary hemorrhage": "Xuất huyết phổi",
    "Circulatory collapse": "Suy tuần hoàn",
    "Dysthymia": "Rối loạn khí sắc",
    "Gastric outlet obstruction": "Tắc nghẽn lối ra dạ dày",
    "Anal fissure": "Nứt hậu môn",
    "Hypertrichosis": "Rậm lông bất thường",
    "Tachyphylaxis": "Quen thuốc nhanh",
    "Nerve injury": "Tổn thương thần kinh",
    "Rectal pain": "Đau trực tràng",
    "Intestinal ischemia": "Thiếu máu ruột",
    "Gastric distension": "Chướng dạ dày",
    "Apprehension": "Lo âu",
    "Cirrhosis": "Xơ gan",
    "Uterine tachysystole": "Co tử cung nhanh",
    "Arterial occlusion": "Tắc động mạch",
    "Vaginitis": "Viêm âm đạo",
    "Steatorrhea": "Phân mỡ",
    "Ovarian cyst": "Nang buồng trứng",
    "Constrictive pericarditis": "Viêm màng ngoài tim co thắt",
    "Cervical intraepithelial neoplasia": "Tân sản nội biểu mô cổ tử cung",
    "Hypochloremia": "Giảm clo máu",
    "Urinary bladder disease": "Bệnh bàng quang",
    "Cardiomegaly": "Tim to",
    "Pyuria": "Mủ niệu",
    "Hemolysis": "Tán huyết",
    "Hypopnea": "Giảm thở",
    "Pseudofolliculitis barbae": "Viêm nang giả vùng râu",
    "Intravascular hemolysis": "Tán huyết trong mạch",
    "Fibrosing colonopathy": "Bệnh đại tràng xơ hóa",
    "Peliosis hepatis": "Bệnh gan thể tím",
    "Dysuria": "Tiểu khó",
    "Apnea": "Ngưng thở",
    "Coarse facial features": "Khuôn mặt thô",
    "Reflex bradycardia": "Nhịp chậm phản xạ",
    "Cyanosis": "Tím tái",
    "Eczema vaccinatum": "Eczema do vắc-xin",
    "Hyperalgesia": "Tăng đau",
    "Thoracic outlet syndrome": "Hội chứng lối thoát ngực",
    "Prion": "Prion",
    "Frontotemporal dementia": "Sa sút trí tuệ trán-thái dương",
    "Wiskott–Aldrich syndrome": "Hội chứng Wiskott-Aldrich",
    "Hypothyroidism": "Suy giáp",
    "Frostbite": "Bỏng lạnh",
    "Meningitis": "Viêm màng não",
    "Epiglottitis": "Viêm nắp thanh quản",
    "Leptospirosis": "Bệnh Leptospira",
    "Hereditary spherocytosis": "Hồng cầu hình cầu di truyền",
    "Kwashiorkor": "Suy dinh dưỡng thể phù",
    "Vascular dementia": "Sa sút trí tuệ mạch máu",
    "Labyrinthitis": "Viêm mê đạo",
    "Cryptosporidiosis": "Bệnh Cryptosporidium",
    "Epidural abscess": "Áp xe ngoài màng cứng",
    "Primary aldosteronism": "Cường aldosteron nguyên phát",
    "Gestational diabetes": "Đái tháo đường thai kỳ",
    "Beta thalassemia": "Thalassemia beta",
    "Pyloric stenosis": "Hẹp môn vị",
    "Essential tremor": "Run vô căn",
    "Pressure ulcer": "Loét do tỳ đè",
    "Otitis media": "Viêm tai giữa",
    "Inguinal hernia": "Thoát vị bẹn",
    "Pharyngitis": "Viêm họng",
    "Acanthosis nigricans": "Gai đen",
    "Acute prostatitis": "Viêm tuyến tiền liệt cấp",
    "Alport syndrome": "Hội chứng Alport",
    "Bronchiolitis": "Viêm tiểu phế quản",
    "Carotid artery stenosis": "Hẹp động mạch cảnh",
    "Infectious mononucleosis": "Bệnh tăng bạch cầu đơn nhân nhiễm khuẩn",
    "Dental abscess": "Áp xe răng",
    "Angular cheilitis": "Viêm kẽ mép",
    "Retinoblastoma": "U nguyên bào võng mạc",
    "Pityriasis rosea": "Vảy phấn hồng",
    "Bowel obstruction": "Tắc ruột",
    "Uterine prolapse": "Sa tử cung",
    "Occupational asthma": "Hen nghề nghiệp",
    "Asbestosis": "Bệnh bụi phổi amiăng",
    "Toxic multinodular goitre": "Bướu giáp đa nhân độc",
    "Anorectal abscess": "Áp xe hậu môn trực tràng",
    "Tetralogy of Fallot": "Tứ chứng Fallot",
    "Chronic granulomatous disease": "Bệnh u hạt mạn tính",
    "Laryngomalacia": "Nhuyễn thanh quản",
    "Reactive arthritis": "Viêm khớp phản ứng",
    "Minimal change disease": "Bệnh thay đổi tối thiểu",
    "Placenta praevia": "Nhau tiền đạo",
    "Allergic bronchopulmonary aspergillosis": "Bệnh phổi phế quản dị ứng do Aspergillus",
    "Polymorphous light eruption": "Ban đa dạng do ánh sáng",
    "Infective endocarditis": "Viêm nội tâm mạc nhiễm khuẩn",
    "De Quervains thyroiditis": "Viêm giáp De Quervain",
    "Rhinitis": "Viêm mũi",
    "Ganglion cyst": "Nang bao gân",
    "Pseudohypoparathyroidism": "Giả suy cận giáp",
    "Foodborne illness": "Ngộ độc thực phẩm",
    "Primary ovarian insufficiency": "Suy buồng trứng nguyên phát",
    "Osteochondritis dissecans": "Viêm xương sụn bóc tách",
    "Superior vena cava syndrome": "Hội chứng tĩnh mạch chủ trên",
    "Periodic limb movement disorder": "Rối loạn vận động chi theo chu kỳ",
    "Pyelonephritis": "Viêm bể thận",
    "Abetalipoproteinemia": "Không beta lipoprotein máu",
    "Atypical pneumonia": "Viêm phổi không điển hình",
    "Paraphimosis": "Nghẹt bao quy đầu",
    "Budd–Chiari syndrome": "Hội chứng Budd-Chiari",
    "Fungal meningitis": "Viêm màng não do nấm",
    "Peutz–Jeghers syndrome": "Hội chứng Peutz-Jeghers",
    "Umbilical hernia": "Thoát vị rốn",
    "Postpartum depression": "Trầm cảm sau sinh",
    "Cholesteatoma": "Cholesteatoma",
    "Lichen simplex chronicus": "Lichen đơn dạng mạn tính",
    "Plantar fasciitis": "Viêm cân gan chân",
    "Epidermolysis bullosa": "Ly thượng bì bọng nước",
    "Organophosphate poisoning": "Ngộ độc phospho hữu cơ",
    "Retropharyngeal abscess": "Áp xe thành sau họng",
    "Cryoglobulinemia": "Cryoglobulin máu",
    "Lyme disease": "Bệnh Lyme",
    "Cholecystitis": "Viêm túi mật",
    "Anemia of chronic disease": "Thiếu máu do bệnh mạn tính",
    "Primary polydipsia": "Uống nhiều nguyên phát",
    "Urinary tract infection": "Nhiễm khuẩn đường tiết niệu",
    "Cerebral palsy": "Bại não",
    "Pilonidal disease": "Bệnh nang lông",
    "Pterygium": "Mộng mắt",
    "Glaucoma": "Tăng nhãn áp (Glôcôm)",
    "Adolescent idiopathic scoliosis": "Vẹo cột sống vô căn ở thanh thiếu niên",
    "Medulloblastoma": "U nguyên bào tủy",
    "Normal pressure hydrocephalus": "Não úng thủy áp lực bình thường",
    "Abdominal aortic aneurysm": "Phình động mạch chủ bụng",
    "Prolactinoma": "U tiết prolactin",
    "Benign paroxysmal positional vertigo": "Chóng mặt tư thế kịch phát lành tính",
    "Hiatal hernia": "Thoát vị hoành",
    "Medullary sponge kidney": "Thận xốp tủy",
    "HELLP syndrome": "Hội chứng HELLP",
    "Tension headache": "Đau đầu căng cơ",
    "Ehlers–Danlos syndromes": "Hội chứng Ehlers-Danlos",
    "Viral meningitis": "Viêm màng não do virus",
    "Craniopharyngioma": "U sọ hầu",
    "Cerebral arteriovenous malformation": "Dị dạng động tĩnh mạch não",
    "Varicocele": "Giãn tĩnh mạch thừng tinh",
    "Astigmatism": "Loạn thị",
    "Phytophotodermatitis": "Viêm da quang hóa do thực vật",
    "Trigonocephaly": "Đầu tam giác",
    "Urogenital fistula": "Rò niệu sinh dục",
    "Senter syndrome": "Hội chứng Senter",
    "Stye": "Lẹo mắt",
    "Vitamin deficiency": "Thiếu vitamin",
    "Euthyroid sick syndrome": "Hội chứng bệnh giáp bình giáp",
    "Intertrigo": "Hăm kẽ",
    "Palmoplantar keratoderma": "Dày sừng lòng bàn tay bàn chân",
    "Tuberculosis cutis orificialis": "Lao da lỗ tự nhiên",
    "Lentiginosis": "Đa đồi mồi",
    "Congenital ichthyosiform erythroderma": "Hồng bì vảy cá bẩm sinh",
    "Focal and diffuse brain injury": "Tổn thương não khu trú và lan tỏa",
    "Gleichs syndrome": "Hội chứng Gleich",
    "Non scarring hair loss": "Rụng tóc không sẹo",
    "Chylothorax": "Tràn dưỡng chấp màng phổi",
    "Hydroa vacciniforme": "Mụn nước dạng đậu",
    "Afterimage": "Ảnh tàn dư",
    "Granulomatous mastitis": "Viêm vú u hạt",
    "Acantholytic dyskeratotic epidermal nevus": "Bớt thượng bì loạn sừng ly gai",
    "Acne miliaris necrotica": "Mụn trứng cá hoại tử dạng kê",
    "Heart valve dysplasia": "Loạn sản van tim",
    "Uveitis": "Viêm màng bồ đào",
    "Secondary hypertension": "Tăng huyết áp thứ phát",
    "Vibration white finger": "Ngón tay trắng do rung",
    "Cerebellar stroke syndrome": "Hội chứng đột quỵ tiểu não",
    "Electrical burn": "Bỏng điện",
    "Schizophrenia": "Tâm thần phân liệt",
    "Tietze syndrome": "Hội chứng Tietze",
    "Amyloidosis": "Bệnh amyloid",
    "Social anxiety disorder": "Rối loạn lo âu xã hội",
    "Laryngeal papillomatosis": "U nhú thanh quản",
    "Herpes simplex keratitis": "Viêm giác mạc do herpes simplex",
    "Congenital hypofibrinogenemia": "Giảm fibrinogen máu bẩm sinh",
    "Esophagogastric junction outflow obstruction": "Tắc nghẽn lưu thông chỗ nối thực quản-dạ dày",
    "Viral encephalitis": "Viêm não do virus",
    "Respiratory acidosis": "Toan hô hấp",
    "Krabbe disease": "Bệnh Krabbe",
    "Nystagmus": "Rung giật nhãn cầu",
    "Kawasaki disease": "Bệnh Kawasaki",
    "Neutropenia": "Giảm bạch cầu trung tính",
    "Orofacial granulomatosis": "U hạt miệng-mặt",
    "Dyschromatosis universalis hereditaria": "Rối loạn sắc tố da di truyền toàn thể",
    "Chronic progressive external ophthalmoplegia": "Liệt mắt ngoài tiến triển mạn tính",
    "Pericarditis": "Viêm màng ngoài tim",
    "Synovial chondromatosis": "U sụn bao hoạt dịch",
    "Lacunar stroke": "Đột quỵ lỗ khuyết",
    "Toxic epidermal necrolysis": "Hoại tử thượng bì nhiễm độc",
    "Pneumonia": "Viêm phổi",
    "Sowda": "Bệnh Sowda",
    "Leukoplakia": "Bạch sản",
    "Posterior amorphous corneal dystrophy": "Loạn dưỡng giác mạc vô định hình sau",
    "Dawn phenomenon": "Hiện tượng bình minh",
    "Retinal vasculopathy with cerebral leukoencephalopathy and systemic manifestations": "Bệnh mạch võng mạc kèm bệnh chất trắng não và biểu hiện toàn thân",
    "Thunderclap headache": "Đau đầu sét đánh",
    "Nutritional anemia": "Thiếu máu dinh dưỡng",
    "Myopathy, X-linked, with excessive autophagy": "Bệnh cơ liên kết X với tự thực quá mức",
    "Cutaneous horn": "Sừng da",
    "Lecithin cholesterol acyltransferase deficiency": "Thiếu lecithin cholesterol acyltransferase",
    "Micropsia": "Nhìn nhỏ",
    "Primary progressive aphasia": "Mất ngôn ngữ tiến triển nguyên phát",
    "Coffin–Lowry syndrome": "Hội chứng Coffin-Lowry",
    "Transverse nasal crease": "Nếp gấp ngang mũi",
    "Aniseikonia": "Bất đẳng ảnh",
    "Pulp stone": "Sỏi tủy răng",
    "Microdontia": "Răng nhỏ",
    "Refractory cytopenia with multilineage dysplasia": "Giảm tế bào kháng trị với loạn sản đa dòng",
    "Medulloepithelioma": "U biểu mô tủy",
    "Metastatic calcification": "Vôi hóa di căn",
    "Hereditary breast–ovarian cancer syndrome": "Hội chứng ung thư vú-buồng trứng di truyền",
    "Punctate epithelial erosions": "Trợt biểu mô chấm",
    "Retinitis pigmentosa": "Viêm võng mạc sắc tố",
    "Metabolic acidosis": "Toan chuyển hóa",
    "Placental site nodule": "Nốt vị trí nhau",
    "Spondylosis": "Thoái hóa cột sống",
    "Xanthoma": "U vàng",
    "List of skin conditions": "Danh sách bệnh da liễu",
    "Pruritus of genital organs": "Ngứa cơ quan sinh dục",
    "Gulf War syndrome": "Hội chứng Chiến tranh Vùng Vịnh",
    "Hemophagocytic lymphohistiocytosis": "Bệnh lympho mô bào thực hồng cầu",
    "Carnitine palmitoyltransferase I deficiency": "Thiếu carnitine palmitoyltransferase I",
    "Osteoclast": "Hủy cốt bào",
    "Gallstone": "Sỏi mật",
    "Adenoiditis": "Viêm VA",
    "Keratosis pilaris": "Dày sừng nang lông",
    "Piedraia hortae": "Nấm Piedraia hortae",
    "Extravasation of urine": "Tràn nước tiểu ngoài mạch",
    "Mannosidosis": "Bệnh Mannosidosis",
    "Partial androgen insensitivity syndrome": "Hội chứng không nhạy cảm androgen một phần",
    "Perihepatitis": "Viêm quanh gan",
    "Subarachnoid hemorrhage": "Xuất huyết dưới nhện",
    "Dysequilibrium syndrome": "Hội chứng mất cân bằng",
    "Gingival and periodontal pocket": "Túi nướu và nha chu",
    "Torus": "U xương lành tính",
    "Paronychia": "Chín mé",
    "Acephaly": "Vô đầu",
    "Lung cavity": "Hang phổi",
    "Elective mutism": "Câm chọn lọc",
    "Hypermethioninemia": "Tăng methionine máu",
    "Sideroblastic anemia": "Thiếu máu nguyên hồng cầu sắt",
    "Melanocytic nevus": "Bớt sắc tố",
    "Acute disseminated encephalomyelitis": "Viêm não tủy cấp lan tỏa",
    "Hereditary sclerosing poikiloderma": "Da đa dạng xơ hóa di truyền",
    "Schilders disease": "Bệnh Schilder",
    "Central serous chorioretinopathy": "Bệnh võng mạc-hắc mạc thanh dịch trung tâm",
    "Streptococcal pharyngitis": "Viêm họng do liên cầu",
    "Lipodermatosclerosis": "Xơ hóa da mỡ",
    "Bee sting": "Ong đốt",
    "Nicotine withdrawal": "Cai nicotine",
    "Menopause": "Mãn kinh",
    "Trisomy 9": "Trisomy 9",
    "Nuchal cord": "Dây rốn quấn cổ",
    "Mosquito": "Muỗi",
    "Chromoblastomycosis": "Bệnh nấm sắc tố",
    "Gastric atresia": "Teo dạ dày",
    "Antenatal depression": "Trầm cảm trước sinh",
    "Laryngo-onycho-cutaneous syndrome": "Hội chứng thanh quản-móng-da",
    "Oral mucocele": "Nang nhầy miệng",
    "Fibrous hamartoma of infancy": "Hamartoma xơ ở trẻ nhỏ",
    "Sciatic nerve": "Dây thần kinh tọa",
    "Tufted angioma": "U mạch dạng chùm",
    "Ablepharon macrostomia syndrome": "Hội chứng không mi mắt-miệng rộng",
    "Vitreomacular adhesion": "Dính dịch kính-hoàng điểm",
    "Dental plaque": "Mảng bám răng",
    "Infantile systemic hyalinosis": "Bệnh hyalin toàn thân ở trẻ nhỏ",
    "Popliteal pterygium syndrome": "Hội chứng pterygium khoeo",
    "Perinatal asphyxia": "Ngạt chu sinh",
    "Teratospermia": "Tinh trùng dị dạng",
    "Bakers cyst": "Nang Baker",
    "Reperfusion injury": "Tổn thương tái tưới máu",
    "Rhinolith": "Sỏi mũi",
    "Ectrodactyly": "Thiếu ngón",
    "Trichorrhexis invaginata": "Tóc gãy lồng vào nhau",
    "Muehrckes nails": "Móng Muehrcke",
    "Oxygen toxicity": "Ngộ độc oxy",
    "Yaws": "Bệnh ghẻ cóc",
    "Cutis rhomboidalis nuchae": "Da gáy hình thoi",
    "Dystonia": "Loạn trương lực cơ",
    "Scimitar syndrome": "Hội chứng Scimitar",
    "Melioidosis": "Bệnh Melioidosis",
    "Avoidant personality disorder": "Rối loạn nhân cách tránh né",
    "Pigment dispersion syndrome": "Hội chứng phân tán sắc tố",
    "Fibroma": "U xơ",
    "Bizarre parosteal osteochondromatous proliferation": "Tăng sinh xương sụn cạnh xương bất thường",
    "Stomatitis": "Viêm miệng",
    "Paratyphoid fever": "Sốt phó thương hàn",
    "Ulnar nerve entrapment": "Chèn ép dây thần kinh trụ",
    "Epidermolysis bullosa acquisita": "Ly thượng bì bọng nước mắc phải",
    "Vascular myelopathy": "Bệnh tủy sống mạch máu",
    "Morvans syndrome": "Hội chứng Morvan",
    "Calcific tendinitis": "Viêm gân vôi hóa",
    "Post-kala-azar dermal leishmaniasis": "Leishmania da sau kala-azar",
    "Fordyce spots": "Hạt Fordyce",
    "Linear focal elastosis": "Xơ đàn hồi khu trú tuyến tính",
    "Phalanx bone": "Xương đốt ngón",
    "Irregular sleep–wake rhythm": "Rối loạn nhịp thức-ngủ không đều",
    "Fistula": "Rò",
    "Papillary thyroid cancer": "Ung thư giáp thể nhú",
    "WAGR syndrome": "Hội chứng WAGR",
    "Costello syndrome": "Hội chứng Costello",
    "Skew deviation": "Lệch nhãn cầu",
    "Blistering distal dactylitis": "Viêm ngón xa bọng nước",
    "Mitral regurgitation": "Hở van hai lá",
    "Pyridoxine-dependent epilepsy": "Động kinh phụ thuộc pyridoxine",
    "Hypotension": "Hạ huyết áp",
    "Attenuated familial adenomatous polyposis": "Đa polyp tuyến gia đình thể nhẹ",
    "Coccidioidomycosis": "Bệnh nấm Coccidioides",
    "Filippi syndrome": "Hội chứng Filippi",
    "Endometrial stromal tumour": "U mô đệm nội mạc tử cung",
    "Aerosinusitis": "Viêm xoang do áp suất",
    "Chiari malformation": "Dị dạng Chiari",
    "Stasis dermatitis": "Viêm da ứ đọng",
    "Cystocele": "Sa bàng quang",
    "Distal intestinal obstruction syndrome": "Hội chứng tắc ruột xa",
    "Scoliosis": "Vẹo cột sống",
    "Expressive language disorder": "Rối loạn ngôn ngữ diễn đạt",
    "Acral nevus": "Bớt đầu chi",
    "Sialectasis": "Giãn ống tuyến nước bọt",
    "Retrobulbar bleeding": "Chảy máu sau nhãn cầu",
    "Dermatographic urticaria": "Mề đay vẽ da",
    "Lumbar vertebrae": "Đốt sống thắt lưng",
    "Infantile myofibromatosis": "U xơ cơ ở trẻ nhỏ",
    "Lichen sclerosus": "Lichen xơ teo",
    "Frontal lobe disorder": "Rối loạn thùy trán",
    "Android fat distribution": "Phân bố mỡ kiểu nam",
    "Myxoid liposarcoma": "Sarcom mỡ dạng nhầy",
    "Muscular dystrophy": "Loạn dưỡng cơ",
    "Heart failure with preserved ejection fraction": "Suy tim phân suất tống máu bảo tồn",
    "Personality disorder": "Rối loạn nhân cách",
    "Phobia": "Ám ảnh sợ",
    "Gonorrhea": "Bệnh lậu",
    "Wolff–Parkinson–White syndrome": "Hội chứng Wolff-Parkinson-White",
    "Ventricular septal defect": "Thông liên thất",
    "Yellow fever": "Sốt vàng da",
    "Animal bite": "Động vật cắn",
    "Absence seizure": "Cơn vắng ý thức",
    "Meckels diverticulum": "Túi thừa Meckel",
    "Foreign body in alimentary tract": "Dị vật đường tiêu hóa",
    "Adhesive capsulitis of the shoulder": "Viêm bao khớp dính vai (đông cứng vai)",
    "Takayasus arteritis": "Viêm động mạch Takayasu",
    "Depression in childhood and adolescence": "Trầm cảm ở trẻ em và vị thành niên",
    "Alcoholism": "Nghiện rượu",
    "Chagas disease": "Bệnh Chagas",
    "Behçets disease": "Bệnh Behçet",
    "Feltys syndrome": "Hội chứng Felty",
    "Severe combined immunodeficiency": "Suy giảm miễn dịch kết hợp nặng",
    "Monoclonal gammopathy of undetermined significance": "Bệnh gamma đơn dòng chưa xác định ý nghĩa",
    "Hydrocele": "Tràn dịch tinh mạc",
    "Fetal alcohol spectrum disorder": "Rối loạn phổ rượu bào thai",
    "Childhood obesity": "Béo phì ở trẻ em",
    "Blood transfusion": "Truyền máu",
    "Invasive candidiasis": "Nhiễm nấm Candida xâm lấn",
    "Glycogen storage disease type I": "Bệnh dự trữ glycogen type I",
    "Wilsons disease": "Bệnh Wilson",
    "Cavernous sinus thrombosis": "Huyết khối xoang hang",
    "Meniscus tear": "Rách sụn chêm",
    "Amphetamine dependence": "Phụ thuộc amphetamine",
    "Laryngeal cancer": "Ung thư thanh quản",
    "Ductal carcinoma in situ": "Ung thư biểu mô ống tại chỗ",
    "Vestibular schwannoma": "U dây thần kinh tiền đình",
    "Charcot–Marie–Tooth disease": "Bệnh Charcot-Marie-Tooth",
    "Bad breath": "Hôi miệng",
    "Child abuse": "Bạo hành trẻ em",
    "Tricuspid regurgitation": "Hở van ba lá",
    "Varicose veins": "Giãn tĩnh mạch",
    "Squamous cell skin cancer": "Ung thư tế bào vảy da",
    "Brief psychotic disorder": "Rối loạn loạn thần ngắn",
    "Gestational hypertension": "Tăng huyết áp thai kỳ",
    "Essential thrombocythemia": "Tăng tiểu cầu vô căn",
    "Transient synovitis": "Viêm bao hoạt dịch thoáng qua",
    "Intestinal malrotation": "Xoay bất thường ruột",
    "Iliotibial band syndrome": "Hội chứng dải chậu chày",
    "Constipation in children": "Táo bón ở trẻ em",
    "Corneal abrasion": "Trầy xước giác mạc",
    "Pneumoconiosis": "Bệnh bụi phổi",
    "Bartholins cyst": "Nang tuyến Bartholin",
    "Pagets disease of bone": "Bệnh Paget xương",
    "Focal seizure": "Cơn động kinh khu trú",
    "Bipolar disorder in children": "Rối loạn lưỡng cực ở trẻ em",
    "Mycoplasma": "Mycoplasma",
    "Pulmonary insufficiency": "Suy phổi",
    "Stomach cancer": "Ung thư dạ dày",
    "Snoring": "Ngáy",
    "Breech birth": "Sinh ngôi mông",
    "Eye injury": "Chấn thương mắt",
    "Alcoholic liver disease": "Bệnh gan do rượu",
    "Mycobacterium avium complex": "Phức hợp Mycobacterium avium",
    "SARS": "SARS (Hội chứng hô hấp cấp nặng)",
    "CREST syndrome": "Hội chứng CREST",
    "Chikungunya": "Sốt Chikungunya",
    "Anterior cruciate ligament injury": "Tổn thương dây chằng chéo trước",
    "Rotor syndrome": "Hội chứng Rotor",
    "Erbs palsy": "Liệt Erb",
    "Cutaneous larva migrans": "Ấu trùng di chuyển da",
    "Hypertensive emergency": "Cấp cứu tăng huyết áp",
    "Overlap syndrome": "Hội chứng chồng lấp",
    "Fifth disease": "Bệnh thứ năm",
    "Marfan syndrome": "Hội chứng Marfan",
    "Coccydynia": "Đau xương cụt",
    "Zika fever": "Sốt Zika",
    "Sjögren syndrome": "Hội chứng Sjögren",
    "Inflammatory myopathy": "Bệnh cơ viêm",
    "Hemolytic disease of the newborn": "Bệnh tán huyết ở trẻ sơ sinh",
    "Hand, foot, and mouth disease": "Bệnh tay chân miệng",
    "Sialadenitis": "Viêm tuyến nước bọt",
    "Molluscum contagiosum": "U mềm lây",
    "Drowning": "Đuối nước",
    "Cardiac myxoma": "U nhầy tim",
    "Coarctation of the aorta": "Hẹp eo động mạch chủ",
    "Concussion": "Chấn động não",
    "Costochondritis": "Viêm sụn sườn",
    "Temporomandibular joint dysfunction": "Rối loạn khớp thái dương hàm",
    "VIPoma": "U tiết VIP",
    "Folate deficiency": "Thiếu folate",
    "Bruxism": "Nghiến răng",
    "Dengue fever": "Sốt xuất huyết Dengue",
    "Intracranial aneurysm": "Phình mạch nội sọ",
    "Roseola": "Ban đào",
    "Extrapulmonary tuberculosis": "Lao ngoài phổi",
    "Insect bites and stings": "Côn trùng cắn và đốt",
    "Down syndrome": "Hội chứng Down",
    "Joint dislocation": "Trật khớp",
    "Gilberts syndrome": "Hội chứng Gilbert",
    "Hip dysplasia": "Loạn sản khớp háng",
    "Hypothermia": "Hạ thân nhiệt",
    "Baby colic": "Cơn quấy khóc ở trẻ sơ sinh",
    "Cleft lip and cleft palate": "Khe hở môi và vòm miệng",
    "Cocaine dependence": "Phụ thuộc cocaine",
    "Elder abuse": "Bạo hành người cao tuổi",
    "Factitious disorder": "Rối loạn giả tạo",
    "Acute lymphoblastic leukemia": "Bạch cầu cấp dòng lympho",
    "Bed bug": "Rệp giường",
    "DiGeorge syndrome": "Hội chứng DiGeorge",
    "Patellofemoral pain syndrome": "Hội chứng đau xương bánh chè-đùi",
    "Crohns disease": "Bệnh Crohn",
    "Idiopathic intracranial hypertension": "Tăng áp lực nội sọ vô căn",
    "Eustachian tube dysfunction": "Rối loạn vòi nhĩ",
    "Ménières disease": "Bệnh Ménière",
    "Hirschsprungs disease": "Bệnh Hirschsprung (phình đại tràng bẩm sinh)",
    "Rib fracture": "Gãy xương sườn",
    "Thromboangiitis obliterans": "Viêm tắc mạch huyết khối",
    "Dyshidrosis": "Tổ đỉa",
    "Testicular torsion": "Xoắn tinh hoàn",
    "Pelvic inflammatory disease": "Viêm vùng chậu",
    "Yersinia": "Vi khuẩn Yersinia",
    "Post-nasal drip": "Chảy dịch mũi sau",
    "Rotator cuff tear": "Rách chóp xoay",
    "Aortic regurgitation": "Hở van động mạch chủ",
    "Carbon monoxide poisoning": "Ngộ độc carbon monoxide",
    "Cryptogenic organizing pneumonia": "Viêm phổi tổ chức hóa căn nguyên ẩn",
    "Alpha-thalassemia": "Thalassemia alpha",
    "Actinomycosis": "Bệnh nấm phóng xạ",
    "Dysbarism": "Bệnh do thay đổi áp suất",
    "Tricuspid valve stenosis": "Hẹp van ba lá",
    "Brain abscess": "Áp xe não",
    "Chronic venous insufficiency": "Suy tĩnh mạch mạn tính",
    "Testicular cancer": "Ung thư tinh hoàn",
    "Psittacosis": "Bệnh vẹt",
    "SIDS": "Hội chứng đột tử ở trẻ nhỏ",
    "Electrical injury": "Chấn thương điện",
    "Foreign body aspiration": "Hít dị vật",
    "End-of-life care": "Chăm sóc cuối đời",
    "Androgen insensitivity syndrome": "Hội chứng không nhạy cảm androgen",
    "Conus medullaris": "Nón tủy",
    "Neutral lipid storage disease": "Bệnh dự trữ lipid trung tính",
    "Keratitis": "Viêm giác mạc",
    "Warfarin necrosis": "Hoại tử do Warfarin",
    "SERKAL syndrome": "Hội chứng SERKAL",
    "CRLF1": "CRLF1",
    "Overriding aorta": "Động mạch chủ cưỡi ngựa",
    "Hereditary sensory and autonomic neuropathy": "Bệnh thần kinh cảm giác và tự chủ di truyền",
    "IRAK4": "IRAK4",
    "Cutaneous actinomycosis": "Bệnh actinomycosis da",
    "Congenital contractural arachnodactyly": "Ngón nhện co rút bẩm sinh",
    "Fetishism": "Tôn sùng vật phẩm",
    "RAPADILINO syndrome": "Hội chứng RAPADILINO",
    "DSM-IV codes": "Mã DSM-IV",
    "Iniencephaly": "Dị tật Iniencephaly",
    "Enamel hypoplasia": "Thiểu sản men răng",
    "Vocal cord paresis": "Liệt dây thanh",
    "Tracheobronchitis": "Viêm khí phế quản",
    "Repetitive strain injury": "Tổn thương do vận động lặp đi lặp lại",
    "Reactive airway disease": "Bệnh đường thở phản ứng",
    "Chronic traumatic encephalopathy": "Bệnh não chấn thương mạn tính",
    "Post-schizophrenic depression": "Trầm cảm sau tâm thần phân liệt",
    "Cryptorchidism": "Tinh hoàn ẩn",
    "Cytomegalovirus": "Virus Cytomegalovirus",
    "Steatocystoma simplex": "Nang bã đơn",
    "Generalized eruptive histiocytoma": "U mô bào phát ban toàn thể",
    "Proximal femoral focal deficiency": "Thiếu hụt khu trú đầu gần xương đùi",
    "Cystic eyeball": "Nhãn cầu nang",
    "Lupoid sycosis": "Viêm nang lông dạng lupus",
    "Aneurysm of sinus of Valsalva": "Phình xoang Valsalva",
    "Syringomyelia": "Rỗng tủy sống",
    "Acneiform eruption": "Phát ban dạng trứng cá",
    "Complement 4 deficiency": "Thiếu bổ thể 4",
    "Carrions disease": "Bệnh Carrion",
    "Polyneuropathy": "Viêm đa dây thần kinh",
    "Phantom pain": "Đau chi ma",
    "Coeliac disease": "Bệnh celiac",
    "Lentigo maligna": "Đồi mồi ác tính",
    "Hereditary stomatocytosis": "Hồng cầu miệng di truyền",
    "High-altitude cerebral edema": "Phù não do độ cao",
    "Compensatory hyperhidrosis": "Tăng tiết mồ hôi bù",
    "Desquamative gingivitis": "Viêm nướu bong vảy",
    "Goldenhar syndrome": "Hội chứng Goldenhar",
    "Oculopharyngodistal myopathy": "Bệnh cơ mắt-hầu-ngọn chi",
    "Optic papillitis": "Viêm đầu gai thị",
    "Progressive supranuclear palsy": "Liệt trên nhân tiến triển",
    "8p23.1 duplication syndrome": "Hội chứng lặp đoạn 8p23.1",
    "Brachygnathism": "Hàm ngắn",
    "Mixed affective state": "Trạng thái cảm xúc hỗn hợp",
    "Schistosoma mansoni": "Sán máng Schistosoma mansoni",
    "Kimuras disease": "Bệnh Kimura",
    "Monilethrix": "Tóc chuỗi hạt",
    "Sepiapterin reductase deficiency": "Thiếu sepiapterin reductase",
    "Stretch marks": "Rạn da",
    "Caudal regression syndrome": "Hội chứng thoái triển đuôi",
    "Inflammatory bowel disease": "Bệnh viêm ruột",
    "Winchester syndrome": "Hội chứng Winchester",
    "Hemothorax": "Tràn máu màng phổi",
    "Reflex syncope": "Ngất phản xạ",
    "Juvenile polyposis syndrome": "Hội chứng đa polyp thiếu niên",
    "Primary pigmented nodular adrenocortical disease": "Bệnh vỏ thượng thận nốt sắc tố nguyên phát",
    "Blind loop syndrome": "Hội chứng quai mù",
    "Unibrow": "Lông mày liền",
    "Erythema dyschromicum perstans": "Hồng ban rối loạn sắc tố dai dẳng",
    "Beaus lines": "Đường Beau",
    "Exanthem": "Ban ngoại",
    "Early myoclonic encephalopathy": "Bệnh não giật cơ sớm",
    "Neorickettsia helminthoeca": "Neorickettsia helminthoeca",
    "Atopic dermatitis": "Viêm da cơ địa",
    "Pityriasis rubra pilaris": "Vảy phấn đỏ nang lông",
    "Purpura": "Ban xuất huyết",
    "Peritonsillar abscess": "Áp xe quanh amidan",
    "Dens invaginatus": "Răng lõm vào",
    "Encephalocele": "Thoát vị não-màng não",
    "Nuchal fibroma": "U xơ gáy",
    "Lichen myxedematosus": "Lichen phù niêm",
    "WDR45": "WDR45",
    "Fiddlers neck": "Cổ người kéo đàn",
    "Dysphagia lusoria": "Nuốt khó do bất thường mạch máu",
    "Haemodialysis-associated amyloidosis": "Bệnh amyloid liên quan chạy thận nhân tạo",
    "Morphea": "Xơ cứng bì khu trú",
    "Nonvenereal endemic syphilis": "Giang mai địa phương không lây qua đường tình dục",
    "Diabetes": "Đái tháo đường",
    "Coagulation factor VII": "Yếu tố đông máu VII",
    "Auditory processing disorder": "Rối loạn xử lý thính giác",
    "Williams syndrome": "Hội chứng Williams",
    "Generalized pustular psoriasis": "Vảy nến mủ toàn thể",
    "Plasma cell leukemia": "Bạch cầu tương bào",
    "Vernal keratoconjunctivitis": "Viêm kết giác mạc mùa xuân",
    "Synchysis scintillans": "Dịch kính lấp lánh",
    "Sickle cell retinopathy": "Bệnh võng mạc hồng cầu liềm",
    "Hemifacial microsomia": "Thiểu sản nửa mặt",
    "Gradenigos syndrome": "Hội chứng Gradenigo",
    "Photic retinopathy": "Bệnh võng mạc do ánh sáng",
    "Alopecia totalis": "Rụng tóc toàn bộ đầu",
    "Lupus vulgaris": "Lupus thông thường (lao da)",
    "Meconium peritonitis": "Viêm phúc mạc phân su",
    "Occult macular dystrophy": "Loạn dưỡng hoàng điểm ẩn",
    "Cold injury": "Tổn thương do lạnh",
    "Chilblains": "Cước",
    "Savant syndrome": "Hội chứng Savant",
    "Pott disease": "Bệnh Pott (lao cột sống)",
    "Drug-induced lupus erythematosus": "Lupus ban đỏ do thuốc",
    "Anisomelia": "Bất đẳng chi",
    "Spigelian hernia": "Thoát vị Spiegel",
    "Brachydactyly": "Ngón ngắn",
    "Aquagenic urticaria": "Mề đay do nước",
    "Acute uric acid nephropathy": "Bệnh thận acid uric cấp",
    "Median nail dystrophy": "Loạn dưỡng móng giữa",
    "Cyclothymia": "Rối loạn khí sắc chu kỳ",
    "Hydrothorax": "Tràn dịch màng phổi",
    "Pseudostrabismus": "Giả lác",
    "Tooth decay": "Sâu răng",
    "Molar incisor hypomineralisation": "Thiểu khoáng hóa răng hàm-cửa",
    "Heavy chain disease": "Bệnh chuỗi nặng",
    "Focal facial dermal dysplasia": "Loạn sản da mặt khu trú",
    "Ventricular outflow tract obstruction": "Tắc nghẽn đường ra thất",
    "Bunion": "Biến dạng ngón chân cái",
    "Acral fibrokeratoma": "U xơ sừng đầu chi",
    "Schwannoma": "U bao dây thần kinh",
    "Subacute lymphocytic thyroiditis": "Viêm giáp bạch cầu lympho bán cấp",
    "Hyperacusis": "Tăng cảm thính giác",
    "Lassa fever": "Sốt Lassa",
    "Hereditary spastic paraplegia": "Liệt cứng hai chi dưới di truyền",
    "Barbiturate overdose": "Quá liều barbiturate",
    "Conversion disorder": "Rối loạn chuyển đổi",
    "Kabuki syndrome": "Hội chứng Kabuki",
    "Bethlem myopathy": "Bệnh cơ Bethlem",
    "Minimally conscious state": "Trạng thái ý thức tối thiểu",
    "Retiform parapsoriasis": "Cận vảy nến dạng lưới",
    "Perforating granuloma annulare": "U hạt dạng vòng xuyên thấu",
    "Erdheim–Chester disease": "Bệnh Erdheim-Chester",
    "Dentigerous cyst": "Nang thân răng",
    "Granular cell tumor": "U tế bào hạt",
    "Butchers wart": "Mụn cóc người bán thịt",
    "Human penis size": "Kích thước dương vật người",
    "Occlusal trauma": "Sang chấn khớp cắn",
    "Linear verrucous epidermal nevus": "Bớt thượng bì dạng mụn cóc tuyến tính",
    "Bálints syndrome": "Hội chứng Bálint",
    "Hemiballismus": "Múa giật nửa người",
    "Sensorineural hearing loss": "Nghe kém tiếp nhận",
    "Triphalangeal thumb": "Ngón cái ba đốt",
    "Vitiligo": "Bạch biến",
    "Thin basement membrane disease": "Bệnh màng đáy mỏng",
    "Dislocated shoulder": "Trật khớp vai",
    "Neonatal hepatitis": "Viêm gan sơ sinh",
    "Amastia": "Không có vú",
    "Pseudoexfoliation syndrome": "Hội chứng giả bong vảy",
    "Complement deficiency": "Thiếu bổ thể",
    "Gustatory hyperhidrosis": "Tăng tiết mồ hôi do vị giác",
    "Vasodilatory shock": "Sốc giãn mạch",
    "Epithelioid hemangioendothelioma": "U nội mô mạch máu dạng biểu mô",
    "Acute proliferative glomerulonephritis": "Viêm cầu thận tăng sinh cấp",
    "Focal dermal hypoplasia": "Thiểu sản da khu trú",
    "Rubeosis iridis": "Tân mạch mống mắt",
    "Wernicke–Korsakoff syndrome": "Hội chứng Wernicke-Korsakoff",
    "Pneumothorax": "Tràn khí màng phổi",
    "Subglottic stenosis": "Hẹp dưới thanh môn",
    "Arrhythmogenic cardiomyopathy": "Bệnh cơ tim gây loạn nhịp",
    "Mastocytosis": "Bệnh tế bào mast",
    "Arthrofibrosis": "Xơ hóa khớp",
    "Oil acne": "Mụn trứng cá do dầu",
    "Pulmonary alveolar microlithiasis": "Vi sỏi phế nang",
    "Gastrocutaneous syndrome": "Hội chứng dạ dày-da",
    "Arthritis": "Viêm khớp",
    "Pesticide poisoning": "Ngộ độc thuốc trừ sâu",
    "Scleroderma": "Xơ cứng bì",
    "Pulmonary hyalinizing granuloma": "U hạt hyalin hóa phổi",
    "Netherton syndrome": "Hội chứng Netherton",
    "Congenital hepatic fibrosis": "Xơ gan bẩm sinh",
    "Polycythemia": "Đa hồng cầu",
    "Velopharyngeal insufficiency": "Thiểu năng vòm hầu",
    "Emphysema": "Khí phế thũng",
    "Essential fatty acid": "Axit béo thiết yếu",
    "Toxic shock syndrome": "Hội chứng sốc nhiễm độc",
    "Biliary dyskinesia": "Rối loạn vận động mật",
    "Maturity-onset diabetes of the young": "Đái tháo đường khởi phát trưởng thành ở người trẻ",
    "Syringofibroadenoma": "U tuyến xơ ống mồ hôi",
    "Encephalitis lethargica": "Viêm não ngủ",
    "Phaeohyphomycosis": "Bệnh nấm sợi đen",
    "Birth weight": "Cân nặng lúc sinh",
    "Heerfordt syndrome": "Hội chứng Heerfordt",
    "Campomelic dysplasia": "Loạn sản xương cong",
    "Ovarian remnant syndrome": "Hội chứng mô buồng trứng còn sót",
    "Learning disability": "Khuyết tật học tập",
    "Caput succedaneum": "Bướu thanh huyết",
    "Necrotizing bronchiolitis": "Viêm tiểu phế quản hoại tử",
    "Decapitation": "Chặt đầu",
    "Postpartum psychosis": "Loạn thần sau sinh",
    "Müllerian agenesis": "Không phát triển ống Müller",
    "X-linked dystonia parkinsonism": "Loạn trương lực-parkinson liên kết X",
    "Postpartum thyroiditis": "Viêm giáp sau sinh",
    "Argyria": "Bệnh da bạc",
    "Pitted keratolysis": "Viêm sừng lõm",
    "Congenital dyserythropoietic anemia": "Thiếu máu loạn sinh hồng cầu bẩm sinh",
    "GM1 gangliosidoses": "Bệnh ganglioside GM1",
    "Hepatoblastoma": "U nguyên bào gan",
    "Erythropoietic protoporphyria": "Protoporphyria sinh hồng cầu",
    "Cerebrospinal fluid leak": "Rò dịch não tủy",
    "Acute motor axonal neuropathy": "Bệnh thần kinh sợi trục vận động cấp",
    "Ataque de nervios": "Ataque de nervios (cơn loạn thần kinh)",
    "Umbilical cord compression": "Chèn ép dây rốn",
    "Keratoderma": "Dày sừng",
    "Laryngospasm": "Co thắt thanh quản",
    "Posterior cerebral artery syndrome": "Hội chứng động mạch não sau",
    "Interrupted aortic arch": "Gián đoạn cung động mạch chủ",
    "Pendular nystagmus": "Rung giật nhãn cầu dạng lắc",
    "Intraocular lens": "Thủy tinh thể nhân tạo",
    "Glucose-6-phosphate dehydrogenase deficiency": "Thiếu G6PD",
    "Megaesophagus": "Thực quản giãn to",
    "Subdural hygroma": "Tụ dịch dưới màng cứng",
    "Pseudolymphoma": "Giả lymphoma",
    "Early pregnancy bleeding": "Chảy máu thai kỳ sớm",
    "Hemimegalencephaly": "Phì đại nửa não",
    "Polysyndactyly": "Dính-thừa ngón",
    "Peripheral artery disease": "Bệnh động mạch ngoại biên",
    "Bloom syndrome": "Hội chứng Bloom",
    "Mirizzis syndrome": "Hội chứng Mirizzi",
    "Keratosis pilaris atrophicans": "Dày sừng nang lông teo",
    "Retinal correspondence": "Tương ứng võng mạc",
    "Gonadal dysgenesis": "Loạn phát triển tuyến sinh dục",
    "Hot tub folliculitis": "Viêm nang lông do bồn tắm nóng",
    "Vocal cord hemorrhage": "Xuất huyết dây thanh",
    "Erythema elevatum diutinum": "Hồng ban nổi cao kéo dài",
    "Early onset dementia": "Sa sút trí tuệ khởi phát sớm",
    "Gingival enlargement": "Phì đại nướu",
    "Nasal glial heterotopia": "Lạc chỗ thần kinh đệm mũi",
    "Webbed penis": "Dương vật có màng",
    "Sarcoidosis": "Bệnh Sarcoid",
    "Glossitis": "Viêm lưỡi",
    "Placental site trophoblastic tumor": "U nguyên bào nuôi vị trí nhau",
    "Ureterovaginal fistula": "Rò niệu quản-âm đạo",
    "Tardive dyskinesia": "Loạn động muộn",
    "Acute necrotizing ulcerative gingivitis": "Viêm nướu loét hoại tử cấp",
    "Posthitis": "Viêm bao quy đầu",
    "Epidural hematoma": "Tụ máu ngoài màng cứng",
    "Palmar erythema": "Hồng ban lòng bàn tay",
    "Myotonic dystrophy": "Loạn dưỡng cơ trương lực",
    "Monofixation syndrome": "Hội chứng cố định một mắt",
    "Toxic and nutritional optic neuropathy": "Bệnh thần kinh thị giác do độc chất và dinh dưỡng",
    "Microspherophakia": "Thủy tinh thể hình cầu nhỏ",
    "Syphilis": "Giang mai",
    "Lymphomatoid granulomatosis": "U hạt dạng lymphoma",
    "Acute interstitial pneumonitis": "Viêm phổi kẽ cấp",
    "Exophoria": "Ngoại ẩn lác",
    "Genetics of obesity": "Di truyền học béo phì",
    "Pulmonary capillary hemangiomatosis": "U mao mạch phổi",
    "Ocular rosacea": "Trứng cá đỏ mắt",
    "Claudes syndrome": "Hội chứng Claude",
    "Plasma cell dyscrasias": "Bệnh loạn tương bào",
    "Hemotympanum": "Tràn máu hòm nhĩ",
    "Chondrodermatitis nodularis chronica helicis": "Viêm sụn da nốt mạn tính vành tai",
    "Phenylketonuria": "Bệnh phenylketon niệu",
    "Folie à deux": "Rối loạn loạn thần chia sẻ",
    "Self-harm": "Tự gây thương tích",
    "Separation anxiety disorder": "Rối loạn lo âu chia ly",
    "Nevus lipomatosus superficialis": "Bớt mỡ nông",
    "Spina bifida": "Nứt đốt sống",
    "Waldmann disease": "Bệnh Waldmann",
    "Hypermobility spectrum disorder": "Rối loạn phổ siêu di động khớp",
    "Ventricular aneurysm": "Phình thất",
    "Dissecting cellulitis of the scalp": "Viêm mô tế bào bóc tách da đầu",
    "Ligamentous laxity": "Lỏng lẻo dây chằng",
    "Thoracic insufficiency syndrome": "Hội chứng suy lồng ngực",
    "Noma (disease)": "Bệnh Noma (cam tẩu mã)",
    "Lymphangitis carcinomatosa": "Viêm bạch mạch ung thư",
    "Pleural thickening": "Dày màng phổi",
    "Acheiropodia": "Không có tay chân",
    "Parasystole": "Nhịp phụ",
    "Phocomelia": "Dị tật chi dạng hải cẩu",
    "Nephrocalcinosis": "Vôi hóa thận",
    "Exotropia": "Lé ngoài",
    "Episodic ataxia": "Thất điều từng cơn",
    "Mouth ulcer": "Loét miệng",
    "Hospitalism": "Hội chứng nhập viện",
    "Pseudohypoaldosteronism": "Giả giảm aldosteron",
    "Ischial bursitis": "Viêm bao hoạt dịch ụ ngồi",
    "Caffeine-induced anxiety disorder": "Rối loạn lo âu do caffeine",
    "Pathological demand avoidance": "Né tránh yêu cầu bệnh lý",
    "Malakoplakia": "Malakoplakia",
    "Bartons fracture": "Gãy Barton",
    "Megaduodenum": "Tá tràng giãn to",
    "Werner syndrome": "Hội chứng Werner",
    "Haemophilia C": "Hemophilia C",
    "Imperforate anus": "Hậu môn không thủng",
    "Phlyctenular keratoconjunctivitis": "Viêm kết giác mạc bọng",
    "Chilblain lupus erythematosus": "Lupus ban đỏ dạng cước",
    "Multicentric carpotarsal osteolysis syndrome": "Hội chứng tiêu xương cổ tay-cổ chân đa ổ",
    "Myeloid sarcoma": "Sarcom dòng tủy",
    "Hand eczema": "Chàm tay",
    "Hyperestrogenism": "Cường estrogen",
    "Postcholecystectomy syndrome": "Hội chứng sau cắt túi mật",
    "Biphenotypic acute leukaemia": "Bạch cầu cấp hai dòng",
    "Fungal infection": "Nhiễm nấm",
    "Skin manifestations of sarcoidosis": "Biểu hiện da của bệnh sarcoid",
    "Laurence–Moon syndrome": "Hội chứng Laurence-Moon",
    "Fuchs dystrophy": "Loạn dưỡng Fuchs",
    "Inappropriate sinus tachycardia": "Nhịp nhanh xoang không thích hợp",
    "Systemic scleroderma": "Xơ cứng bì toàn thân",
    "Hair follicle nevus": "Bớt nang lông",
    "Intrauterine growth restriction": "Thai chậm tăng trưởng trong tử cung",
    "Iridocorneal endothelial syndrome": "Hội chứng nội mô mống mắt-giác mạc",
    "Pityriasis": "Vảy phấn",
    "Tic disorder": "Rối loạn tic",
    "Superior canal dehiscence syndrome": "Hội chứng hở ống bán khuyên trên",
    "Poliosis": "Bạc tóc khu trú",
    "Major aortopulmonary collateral artery": "Động mạch bàng hệ chủ-phổi lớn",
    "Autosomal recessive axonal neuropathy with neuromyotonia": "Bệnh thần kinh sợi trục lặn NST thường kèm co cơ",
    "Arachnodactyly": "Ngón nhện",
    "Secondary sclerosing cholangitis": "Viêm đường mật xơ hóa thứ phát",
    "Dermatophytosis": "Nấm ngoài da",
    "9q34.3 deletion syndrome": "Hội chứng mất đoạn 9q34.3",
    "Nonpuerperal mastitis": "Viêm vú không do cho con bú",
    "Juvenile hemochromatosis": "Nhiễm sắt mô thiếu niên",
    "Cherry angioma": "U mạch dạng anh đào",
    "Ectromelia": "Thiếu chi",
    "Triplegia": "Liệt ba chi",
    "Hypolipoproteinemia": "Giảm lipoprotein máu",
    "Cervicocranial syndrome": "Hội chứng cổ-sọ",
    "Idiopathic pure sudomotor failure": "Suy tiết mồ hôi vô căn đơn thuần",
    "Glomeruloid hemangioma": "U mạch dạng cầu thận",
    "Ludwigs angina": "Viêm tấy Ludwig"

}
# Write Part 1
with open("part1.txt", "w", encoding="utf-8") as f:
    for en, vi in translations.items():
        f.write(f"{vi}\n")

print(f"Part 1: {len(translations)} terms written")